### ISSUE TITLE
Nor di nötige values iläse

### ISSUE THREAD

**Issue by lbrndnr** [Hadjimina/C-exercises#2]
[srsly](https://github.com/Hadjimina/C-exercises/blob/master/Ex%203/io.c#L28)

**Comment by Hadjimina** [comment]
Issue from people who stink will automatically be closed. Thank you for understanding.
P.S. you stink

**Comment by lbrndnr** [comment]
![tbhjuststop_2015-aug-22](https://cloud.githubusercontent.com/assets/762049/19263408/7decdcd6-8f9c-11e6-8ccd-8ba75a8b8c37.jpg)

**Comment by lbrndnr** [comment]
![tbhjuststop_2015-aug-22](https://cloud.githubusercontent.com/assets/762049/19263414/8a0f25be-8f9c-11e6-969c-41c929ed6e39.jpg)

**Comment by lbrndnr** [comment]
![tbhjuststop_2015-aug-22](https://cloud.githubusercontent.com/assets/762049/19263431/9c70bfec-8f9c-11e6-9261-e3ef2c1349ad.jpg)
