### ISSUE TITLE
Report.txt not aligned

### ISSUE THREAD

**Issue by lbrndnr** [Hadjimina/C-exercises#3]
Tabs sötte nachm assignment aligned si  
![ryancduff_2015-jul-25](https://cloud.githubusercontent.com/assets/762049/19263383/5720461a-8f9c-11e6-981c-30b188571d3a.jpg)

**Comment by Hadjimina** [comment]
Not playing by the rules ![thug life](http://i.imgur.com/7ZN5vw9.png)
